name: Polaroid Wallpaper CI

on: [push, pull_request]

jobs:
  build:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Run type check
        run: npm run tscheck
      - name: Run biome
        run: npm run lint
